### ISSUE TITLE
FIX 메소드 변경

### ISSUE THREAD

**Issue by www-castlehi-com** [moong2/woowa-precourse-java_baseball_6#10]
## Description
메소드 접근 지정자 변경 및 수정

## ToDo
- [x] Inning class의 endInning()을 private으로 변경
- [x] Inning class의 printResult() 삭제 -> Result 클래스 위임
- [x] Result class의 printStrike(), printBall()을 printResult()로 변경

**Comment by www-castlehi-com** [comment]
해당 이슈에 따른 테스트 코드의 변화

TEST
- [x] Result의 생성자를 호출할 때 Status로 감싸기
