### ISSUE TITLE
FEAT 기능 구현

### ISSUE THREAD

**Issue by www-castlehi-com** [moong2/woowa-precourse-java_baseball_6#13]
## Description
각각의 기능 구현

## ToDo
- [x] 게임, 이닝을 초기화한다.
- [x] Computer의 정답 수를 구한다.
- [x] 정답 수가 유효한지 확인한다.
- [x] 사용자 입력 수를 받는다.
- [x] 입력 수가 유효한지 확인한다.
- [x] 비교한다.
- [x] 3스트라이크가 아닐 경우 출력하고 다시 사용자 입력 수를 받는 곳으로 돌아간다.
- [x] 3스트라이크일 경우 이닝을 종료한다.
- [x] 재시작 / 종료 입력을 받는다.
- [x] 유효성을 검사한다.
- [x] 완전히 종료하거나 재시작한다.

**Comment by www-castlehi-com** [comment]
FIX
- Number를 list로 Numbers 클래스 생성
- Player의 멤버를 Numbers로 변경

TEST
- getXDigit() 메소드 Number -> Numbers로 이전
- NumberTest에 Number가 음수일 경우 IllegalArgumentException 반환 테스트 추가
- NumberTest에 Number가 4이상일 경우 IllegalArgumentException 반환 테스트 추가
