### ISSUE TITLE
REFACTORING

### ISSUE THREAD

**Issue by www-castlehi-com** [moong2/woowa-precourse-java_baseball_6#17]
## Description
코드 리팩토링

## ToDo
- [x] inning null 반환 변경
- [x] Magic Number 삭제
- [x] 삼항연산자 삭제
- [x] boolean 반환 메소드 간소화
- [x] Numbers-immutable하게 유지
- [x] 에러 메시지 구체화
- [x] Validator 분할 클래스
