### ISSUE TITLE
DOCS 테스트 사항 변경

### ISSUE THREAD

**Issue by www-castlehi-com** [moong2/woowa-precourse-java_baseball_6#6]
## Description
docs/README.md에서 테스트 사항 변경

## ToDo
- [x] 불필요한 테스트 삭제 및 보완

**Comment by www-castlehi-com** [comment]
- [x] GameTest에서 Inning의 정상적 종료 여부와 상관없이 테스트
- [x] InningTest에서 Inning의 비정상적 종료 문구 Player의 validateNumber()로 인가
- [x] UserTest, ComputerTest에서 세 자리 숫자가 아닐 경우와 음수일 경우로 수정
- [x] ResultTest에서 printStrike(), printBall() 나누지 않고 printResult()로 수정
